/**
 * 文件说明：popup 页面元素收集层。
 * 职责：集中获取 popup 页面所需 DOM 元素，供装配层统一使用。
 */

/**
 * 收集 popup 页面需要的 DOM 元素引用。
 */
export function collectPopupElements(doc = document) {
    const byId = (id) => doc.getElementById(id);

    const displayModeSlider = byId('displayModeSlider');
    const annotationModeSlider = byId('annotationModeSlider');
    const dedupeModeSlider = byId('dedupeModeSlider');
    const siteBlockModeSlider = byId('siteBlockModeSlider');

    const pageIds = [
        'pageMain',
        'pageVocab',
        'pageAdvanced',
        'pageStyle',
        'pageAnnotation',
        'pageWordInfo',
        'pageWordCardSettings',
        'pageBlocked',
        'pageFavorites',
        'pageSiteBlock',
        'pageSiteRule',
        'pageSync',
        'pageAbout',
        'pageAISettings',
        'pageQuickAnnotationBehavior'
    ];
    const [
        pageMain,
        pageVocab,
        pageAdvanced,
        pageStyle,
        pageAnnotation,
        pageWordInfo,
        pageWordCardSettings,
        pageBlocked,
        pageFavorites,
        pageSiteBlock,
        pageSiteRule,
        pageSync,
        pageAbout,
        pageAISettings,
        pageQuickAnnotationBehavior
    ] = pageIds.map(byId);

    const navIds = [
        'vocabBack', 'advancedBack', 'styleNav', 'annotationNav', 'wordCardSettingsNav', 'blockedNav', 'favoritesNav',
        'vocabularyNav', 'siteBlockNav', 'syncNav', 'aboutNav', 'aiSettingsBack', 'styleBack', 'annotationBack',
        'wordCardSettingsBack', 'wordInfoBack', 'blockedBack', 'favoritesBack', 'siteBlockBack', 'siteRuleBack', 'aboutBack'
    ];
    const [
        vocabBack,
        advancedBack,
        styleNav,
        annotationNav,
        wordCardSettingsNav,
        blockedNav,
        favoritesNav,
        vocabularyNav,
        siteBlockNav,
        syncNav,
        aboutNav,
        aiSettingsBack,
        styleBack,
        annotationBack,
        wordCardSettingsBack,
        wordInfoBack,
        blockedBack,
        favoritesBack,
        siteBlockBack,
        siteRuleBack,
        aboutBack
    ] = navIds.map(byId);

    return {
        mainSearchInput: byId('mainSearchInput'),
        mainSearchButton: byId('mainSearchButton'),
        mainSyncPlaceholderBtn: byId('mainSyncPlaceholderBtn'),
        mainSearchPanel: byId('mainSearchPanel'),
        mainSearchResultMeta: byId('mainSearchResultMeta'),
        mainSearchResults: byId('mainSearchResults'),
        displayModeLabelText: byId('displayModeLabelText'),
        displayModeSlider,
        displayModeQuickCard: byId('displayModeQuickCard'),
        openQuickAnnotationBehaviorPageBtn: byId('openQuickAnnotationBehaviorPageBtn'),
        displayModeThumb: displayModeSlider.closest('.mode-slider-container').querySelector('.mode-slider-thumb'),
        displayModeLabels: displayModeSlider.closest('.mode-slider-container').querySelectorAll('.mode-label'),
        annotationModeSlider,
        annotationModeThumb: annotationModeSlider.closest('.mode-slider-container').querySelector('.mode-slider-thumb'),
        annotationModeLabels: annotationModeSlider.closest('.mode-slider-container').querySelectorAll('.mode-label'),
        dedupeModeSlider,
        dedupeModeThumb: dedupeModeSlider.closest('.mode-slider-container').querySelector('.mode-slider-thumb'),
        dedupeModeLabels: dedupeModeSlider.closest('.mode-slider-container').querySelectorAll('.mode-label'),
        siteBlockModeSlider,
        siteBlockModeThumb: siteBlockModeSlider ? siteBlockModeSlider.closest('.mode-slider-container').querySelector('.mode-slider-thumb') : null,
        siteBlockModeLabels: siteBlockModeSlider ? siteBlockModeSlider.closest('.mode-slider-container').querySelectorAll('.mode-label') : [],
        advancedToggle: byId('advancedToggle'),
        vocabularyToggle: byId('vocabularyToggle'),
        vocabularyContent: byId('vocabularyContent'),
        pageMain,
        pageVocab,
        pageAdvanced,
        pageStyle,
        pageAnnotation,
        pageWordInfo,
        pageWordCardSettings,
        pageBlocked,
        pageFavorites,
        pageSiteBlock,
        pageSiteRule,
        pageSync,
        pageAbout,
        pageAISettings,
        pageQuickAnnotationBehavior,
        vocabBack,
        advancedBack,
        styleNav,
        annotationNav,
        wordCardSettingsNav,
        blockedNav,
        favoritesNav,
        vocabularyNav,
        siteBlockNav,
        syncNav,
        aboutNav,
        aiSettingsBack,
        styleBack,
        annotationBack,
        wordCardSettingsBack,
        wordInfoBack,
        blockedBack,
        favoritesBack,
        siteBlockBack,
        siteRuleBack,
        aboutBack,
        syncBack: byId('syncBack'),
        aboutVersion: byId('aboutVersion'),
        oobe: byId('oobe'),
        oobeNext1: byId('oobeNext1'),
        oobeNext2: byId('oobeNext2'),
        oobeOpenDownload: byId('oobeOpenDownload'),
        oobeGoExample: byId('oobeGoExample'),
        oobeSkip: byId('oobeSkip'),
        oobeSteps: Array.from(doc.querySelectorAll('.oobe-step')),
        oobeTitle1: byId('oobeTitle1'),
        oobeText1: byId('oobeText1'),
        oobeTitle2: byId('oobeTitle2'),
        oobeText2: byId('oobeText2'),
        oobeTitle3: byId('oobeTitle3'),
        oobeText3: byId('oobeText3'),
        oobeVocabList: byId('oobeVocabList'),
        oobeVocabEmpty: byId('oobeVocabEmpty'),
        importBtn: byId('importBtn'),
        fileInput: byId('fileInput'),
        importStatus: byId('importStatus'),
        vocabSearchInput: byId('vocabSearchInput'),
        updateProgress: byId('updateProgress'),
        updateProgressLabel: byId('updateProgressLabel'),
        updateProgressPercent: byId('updateProgressPercent'),
        updateProgressBar: byId('updateProgressBar'),
        updateOverall: byId('updateOverall'),
        updateOverallLabel: byId('updateOverallLabel'),
        updateOverallPercent: byId('updateOverallPercent'),
        updateOverallBar: byId('updateOverallBar'),
        updateModal: byId('updateModal'),
        updateModalClose: byId('updateModalClose'),
        updateCancelBtn: byId('updateCancelBtn'),
        updateRetryBtn: byId('updateRetryBtn'),
        updateErrorMessage: byId('updateErrorMessage'),
        filesList: byId('filesList'),
        fileCount: byId('fileCount'),
        maxMatchesSlider: byId('maxMatchesSlider'),
        maxMatchesLabel: byId('maxMatchesLabel'),
        maxMatchesInput: byId('maxMatchesInput'),
        minTextLengthSlider: byId('minTextLength'),
        minTextLengthLabel: byId('minTextLengthLabel'),
        dedupeRepeatCountSlider: byId('dedupeRepeatCount'),
        dedupeRepeatCountLabel: byId('dedupeRepeatCountLabel'),
        clearDedupeCountsButton: byId('clearDedupeCounts'),
        dedupeRepeatCountSetting: byId('dedupeRepeatCountSetting'),
        clearDedupeCountsSetting: byId('clearDedupeCountsSetting'),
        highlightModeSelect: byId('highlightMode'),
        highlightColorInput: byId('highlightColor'),
        cnToEnOrderSelect: byId('cnToEnOrder'),
        enToCnOrderSelect: byId('enToCnOrder'),
        disableAnnotationUnderlineToggle: byId('disableAnnotationUnderline'),
        annotationWordCardPopupEnabledToggle: byId('annotationWordCardPopupEnabled'),
        wordCardHighlightMatchedChineseToggle: byId('wordCardHighlightMatchedChinese'),
        speechVoiceSelect: byId('speechVoiceSelect'),
        testChineseVoiceBtn: byId('testChineseVoiceBtn'),
        testEnglishVoiceBtn: byId('testEnglishVoiceBtn'),
        searchProviderSelect: byId('searchProviderSelect'),
        wordInfoSearchBtn: byId('wordInfoSearchBtn'),
        wordInfoFavoriteBtn: byId('wordInfoFavoriteBtn'),
        wordInfoBlockBtn: byId('wordInfoBlockBtn'),
        wordInfoWord: byId('wordInfoWord'),
        wordInfoSpeakBtn: byId('wordInfoSpeakBtn'),
        wordInfoPhonetics: byId('wordInfoPhonetics'),
        wordInfoMeanings: byId('wordInfoMeanings'),
        wordInfoPhrases: byId('wordInfoPhrases'),
        wordInfoExamples: byId('wordInfoExamples'),
        wordInfoSources: byId('wordInfoSources'),
        wordInfoEmpty: byId('wordInfoEmpty'),
        blockedSearchInput: byId('blockedSearchInput'),
        blockedSelectAll: byId('blockedSelectAll'),
        blockedDeleteSelected: byId('blockedDeleteSelected'),
        blockedList: byId('blockedList'),
        blockedImportBtn: byId('blockedImportBtn'),
        blockedExportBtn: byId('blockedExportBtn'),
        blockedImportInput: byId('blockedImportInput'),
        blockedImportModal: byId('blockedImportModal'),
        blockedImportModalClose: byId('blockedImportModalClose'),
        blockedImportFromFileBtn: byId('blockedImportFromFileBtn'),
        blockedImportManualBtn: byId('blockedImportManualBtn'),
        blockedChooseFileBtn: byId('blockedChooseFileBtn'),
        blockedImportFilePane: byId('blockedImportFilePane'),
        blockedImportManualPane: byId('blockedImportManualPane'),
        blockedManualInput: byId('blockedManualInput'),
        blockedManualImportConfirm: byId('blockedManualImportConfirm'),
        blockedImportStatus: byId('blockedImportStatus'),
        favoritesSearchInput: byId('favoritesSearchInput'),
        favoritesSelectAll: byId('favoritesSelectAll'),
        favoritesDeleteSelected: byId('favoritesDeleteSelected'),
        favoritesList: byId('favoritesList'),
        favoritesImportBtn: byId('favoritesImportBtn'),
        favoritesExportBtn: byId('favoritesExportBtn'),
        favoritesImportInput: byId('favoritesImportInput'),
        favoritesImportModal: byId('favoritesImportModal'),
        favoritesImportModalClose: byId('favoritesImportModalClose'),
        favoritesImportFromFileBtn: byId('favoritesImportFromFileBtn'),
        favoritesImportManualBtn: byId('favoritesImportManualBtn'),
        favoritesChooseFileBtn: byId('favoritesChooseFileBtn'),
        favoritesImportFilePane: byId('favoritesImportFilePane'),
        favoritesImportManualPane: byId('favoritesImportManualPane'),
        favoritesManualInput: byId('favoritesManualInput'),
        favoritesManualImportConfirm: byId('favoritesManualImportConfirm'),
        favoritesImportStatus: byId('favoritesImportStatus'),
        siteBlockSearchInput: byId('siteBlockSearchInput'),
        siteBlockSelectAll: byId('siteBlockSelectAll'),
        siteBlockDeleteSelected: byId('siteBlockDeleteSelected'),
        siteBlockList: byId('siteBlockList'),
        siteBlockImportBtn: byId('siteBlockImportBtn'),
        siteBlockExportBtn: byId('siteBlockExportBtn'),
        siteBlockImportInput: byId('siteBlockImportInput'),
        siteBlockImportModal: byId('siteBlockImportModal'),
        siteBlockImportModalClose: byId('siteBlockImportModalClose'),
        siteBlockImportFromFileBtn: byId('siteBlockImportFromFileBtn'),
        siteBlockImportManualBtn: byId('siteBlockImportManualBtn'),
        siteBlockChooseFileBtn: byId('siteBlockChooseFileBtn'),
        siteBlockImportFilePane: byId('siteBlockImportFilePane'),
        siteBlockImportManualPane: byId('siteBlockImportManualPane'),
        siteBlockManualInput: byId('siteBlockManualInput'),
        siteBlockManualImportConfirm: byId('siteBlockManualImportConfirm'),
        siteBlockImportStatus: byId('siteBlockImportStatus'),
        siteBlockTipText: byId('siteBlockTipText'),
        smartSkipCodeLinksToggle: byId('smartSkipCodeLinks'),
        smartSkipEditableTextboxesToggle: byId('smartSkipEditableTextboxes'),
        debugModeToggle: byId('debugMode'),
        resetPopupSizeButton: byId('resetPopupSize'),
        blockSiteBtn: byId('blockSiteBtn'),
        siteBlockQuickCard: byId('siteBlockQuickCard'),
        blockSiteRuleBtn: byId('blockSiteRuleBtn'),
        quickAnnotationBehaviorBack: byId('quickAnnotationBehaviorBack'),
        quickSplitModeSlider: byId('quickSplitModeSlider'),
        quickSplitModeThumb: byId('quickSplitModeSlider')
            ? byId('quickSplitModeSlider').closest('.mode-slider-container').querySelector('.mode-slider-thumb')
            : null,
        quickSplitModeLabels: byId('quickSplitModeSlider')
            ? byId('quickSplitModeSlider').closest('.mode-slider-container').querySelectorAll('.mode-label')
            : [],
        quickDisplayModeCnSlider: byId('quickDisplayModeCnSlider'),
        quickDisplayModeCnThumb: byId('quickDisplayModeCnSlider')
            ? byId('quickDisplayModeCnSlider').closest('.mode-slider-container').querySelector('.mode-slider-thumb')
            : null,
        quickDisplayModeCnLabels: byId('quickDisplayModeCnSlider')
            ? byId('quickDisplayModeCnSlider').closest('.mode-slider-container').querySelectorAll('.mode-label')
            : [],
        quickDisplayModeEnSlider: byId('quickDisplayModeEnSlider'),
        quickDisplayModeEnThumb: byId('quickDisplayModeEnSlider')
            ? byId('quickDisplayModeEnSlider').closest('.mode-slider-container').querySelector('.mode-slider-thumb')
            : null,
        quickDisplayModeEnLabels: byId('quickDisplayModeEnSlider')
            ? byId('quickDisplayModeEnSlider').closest('.mode-slider-container').querySelectorAll('.mode-label')
            : [],
        siteRuleHostInput: byId('siteRuleHostInput'),
        siteRulePageTitle: byId('siteRulePageTitle'),
        siteRuleTipText: byId('siteRuleTipText'),
        siteRuleParentLabel: byId('siteRuleParentLabel'),
        siteRuleExactLabel: byId('siteRuleExactLabel'),
        siteRuleSubdomainLabel: byId('siteRuleSubdomainLabel'),
        siteRuleAddBtn: byId('siteRuleAddBtn'),
        siteRuleStatus: byId('siteRuleStatus'),
        siteBlockQuickTitle: byId('siteBlockQuickTitle'),
        siteBlockQuickTooltip: byId('siteBlockQuickTooltip'),
        syncEnabledToggle: byId('syncEnabledToggle'),
        syncAdvancedOptions: byId('syncAdvancedOptions'),
        syncStatusText: byId('syncStatusText'),
        syncUsageSettingsText: byId('syncUsageSettingsText'),
        syncUsageBlockedText: byId('syncUsageBlockedText'),
        syncUsageFavoritesText: byId('syncUsageFavoritesText'),
        syncUsageSiteRulesText: byId('syncUsageSiteRulesText'),
        syncUsageSettingsBar: byId('syncUsageSettingsBar'),
        syncUsageBlockedBar: byId('syncUsageBlockedBar'),
        syncUsageFavoritesBar: byId('syncUsageFavoritesBar'),
        syncUsageSiteRulesBar: byId('syncUsageSiteRulesBar'),
        syncPushNowBtn: byId('syncPushNowBtn'),
        syncPullNowBtn: byId('syncPullNowBtn'),
        syncConflictEntryBtn: byId('syncConflictEntryBtn'),
        syncConflictModal: byId('syncConflictModal'),
        syncConflictModalClose: byId('syncConflictModalClose'),
        syncConflictCancelBtn: byId('syncConflictCancelBtn'),
        syncConflictRestoreBtn: byId('syncConflictRestoreBtn'),
        syncConflictStatusText: byId('syncConflictStatusText'),
        syncEnableConfirmModal: byId('syncEnableConfirmModal'),
        syncEnableConfirmModalClose: byId('syncEnableConfirmModalClose'),
        syncEnableConfirmCancelBtn: byId('syncEnableConfirmCancelBtn'),
        syncEnableConfirmAcceptBtn: byId('syncEnableConfirmAcceptBtn'),
        syncEnableConfirmChecks: Array.from(doc.querySelectorAll('#syncEnableConfirmChecks input[type="checkbox"]')),
        annotationToAISettingsBtn: byId('annotationToAISettingsBtn'),
        annotationQuickLanguageModeNav: byId('annotationQuickLanguageModeNav'),
        quickFavorites: byId('quickFavorites'),
        quickBlocked: byId('quickBlocked'),
        quickVocab: byId('quickVocab'),
        quickSettings: byId('quickSettings'),
        downloadBtn: byId('downloadBtn'),
        updateAllBtn: byId('updateAllBtn'),
        downloadModal: byId('downloadModal'),
        modalClose: byId('modalClose'),
        loadingSpinner: byId('loadingSpinner'),
        dictList: byId('dictList'),
        dictSearchInput: byId('dictSearchInput'),
        dictTagFilters: byId('dictTagFilters'),
        downloadProgress: byId('downloadProgress'),
        downloadingDict: byId('downloadingDict'),
        downloadErrorOk: byId('downloadErrorOk'),
        progressPercent: byId('progressPercent'),
        progressBar: byId('progressBar')
    };
}
